config/routes.rb
Heliosenergeia::Application.routes.draw do
  get "services/index"

  get "grandprojet/index"

  get "whoarewe/index"
  
  resources :contacts

  get "accueil/index"
  root({:to=>"accueil#index"})

end

app/models/contact.rb
class Contact < ActiveRecord::Base

	validates_presence_of :nom,
						  :message => "Le nom est obligatoire"
						  
#--------------------------------------------------------------
						  
	validates_presence_of :prenom,
						  :message => "Le prénom est obligatoire"

#--------------------------------------------------------------

	validates_presence_of :adresse,
						  :message => "L'adresse est obligatoire"

#--------------------------------------------------------------
	
	validates_presence_of :cp,
						  :message => "Le code postal est obligatoire"
	validates_length_of :cp,
						:in => 5..5,
						:allow_blank => true,
						:too_short => "Le code postal est trop court (5 chiffres min)",
						:too_long => "Le code postal est trop long (5 chiffres max)"
	validates_numericality_of :cp,
							  :on => :create,
							  :allow_blank => true,
							  :message => "Le code postal doit être composé de chiffres uniquement"

#--------------------------------------------------------------
							  
	validates_presence_of :ville,
						  :message => "La ville est obligatoire"
						  
#--------------------------------------------------------------
						  
	validates_format_of :email,
						:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
						:on => :create,
						:allow_blank => true,
						:message => "Le format de l'email est incorrect"
						  
#--------------------------------------------------------------
						  
	validates_presence_of :mobile,
						  :message => "Le téléphone mobile est obligatoire"
	validates_length_of :mobile,
						:in => 10..10,
						:allow_blank => true,
						:too_short => "Le numéro de mobile est trop court (10 chiffres min)",
						:too_long => "Le numéro de mobile est trop long (10 chiffres max)"
	validates_numericality_of :mobile,
							  :on => :create,
							  :allow_blank => true,
							  :message => "Le numéro de téléphone doit être composé de chiffres uniquement"
							  
#--------------------------------------------------------------

	validates_length_of :commentaire,
						:in => 0..500,
						:allow_blank => true,
						:too_long => "Votre commentaire ne doit pas dépasser 500 caractères"
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Vos informations ont été correctement envoyées.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Vos informations ont été correctement modifiées.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/grandprojet_controller.rb
class GrandprojetController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/controllers/whoarewe_controller.rb
class WhoareweController < ApplicationController
  def index
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/grandprojet_helper.rb
module GrandprojetHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/whoarewe_helper.rb
module WhoareweHelper
end

app/views/accueil/index.html.erb
<div id="left">
    <br/>
    <h1>Un placement sûr</h1>
   
    <span class="blue">Rentabilisez votre toit</span>
    <br/>
    <br/>
    N'attendez plus et utilisez votre toiture pour installer des panneaux photovoltaïques. Grâce à l'exposition du soleil sur votre toit tout au long de la journée, les capteurs solaires accumulent de l'énergie électrique que vous pouvez renvendre afin de générer un revenu complementaire. Vendez votre production d'électricite à prix garanti sur une période de 20ans à EDF.
	Ne réfléchissez plus, en installant des panneaux solaire photovoltaïques, vous pouvez percevoir une rente regulière issue de votre installation solaire sur le toit grâce au soleil !
	La rentabilité varie entre 8% et 12% ce qui fait de cette démarche, un investissement sûr qui vous permet d'envisager l'avenir plus sereinement tout en adoptant une attitude responsable et durable pour le respect de l'environnement.   <a href="#">En savoir plus</a>.		<br/>
    <br/>
    <hr >
    <h1>Pourquoi investir </h1>
	<span class="blue">Le photovoltaïque</span>
	<br/><br/>
    Alors que le livret A ne rapporte que 2.25%, investir dans le photovoltaïque est un placement sûr (contrat de rachat sur 20ans) à plus de 8% (rendement supérieur à tout produit financier).
	La France bénéficie du meilleur tarif de rachat, ce qui vous permet d'amortir votre investissement en moins de 10ans. Grâce à l'amortissement exceptionnel, vous pouvez faire baisser votre impôt sur le revenu dès la 1ère année qui suit la réalisation
	des travaux. La loi 2000-108 du 10 février 2000 relative à la modernisation et au developpement du service public de l'électricité a introduit la notion d'obligation d'achat. Ce contrat est etabli pour une durée de 20ans. 
    <br/>
    <br/>
</div>
<br/>
<div id="right"><h1>Histoire</h1><span class="blue">L’énergie solaire photovoltaïque</span><br/>
    <br/>
    
    De la même façon que les plantes utilisent la photosynthèse pour obtenir de l’énergie à partir des rayons du soleil, les modules photovoltaïques convertissent la lumière du soleil en électricité.
	C’est l’effet photovoltaïque, découvert en 1839 par le physicien français Alexandre-Edmond Becquerel.
    <br/>
    <br/>
    L’exploitation industrielle de cette découverte a permis le développement de différentes technologies pour la fabrication des modules photovoltaïques, qui sont les composants essentiels d’une installation de production d’électricité à partir de la lumière du soleil.<br/><br/><br/>
    <br/><br/>
	<h1>Valoriser votre maison</h1><br/>
	l'installation de panneaux solaires photovoltaïques participe fortement à la valorisation de votre maison. Lors de la revente de votre habitation,la présence de panneaux
	photovoltaïques est un réel avantage face aux autres biens immobiliers mis sur le marché dans le secteur. Autant dire que c'est un argument de taille qui est pris en compte
	pour fixer le prix de vente de votre maison. L'installation photovoltaïque apporte une valeur ajoutée qui rendra votre maison plus attractive aux yeux des acheteurs potentiels.
	Il s'agit donc d'un argument important à mettre en avantlors de la revente et des visites éventuelles.  
	<br/><br/>
    <h1>Nos Services</h1>
    <%= image_tag "exunImagesFiles/grenelle.png", :width => "150", :height => "113", :align => "left", :style => "margin-right:10px" %> <span class="blue">Notre savoir-faire à votre service</span><br/><br/>
    Helios Energia met tout en oeuvre afin de garantir le bon déroulement des étapes nécéssaires à la réalisation de votre projet. 
    <br/>
    <br/>
    <br/>
    <br/>
</div>
<div style="clear: both;"></div>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "erreur(s)") %> trouvée(s) dans le formulaire:</h2>

      <ul>
      <% @contact.errors.messages.each do |msg| %>
        <li><%= msg.last.last.html_safe %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="left">
  <div class="field" id="formClient">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :prenom %><br />
    <%= f.text_field :prenom %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :adresse %><br />
    <%= f.text_field :adresse %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :complement %><br />
    <%= f.text_field :complement %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :cp %><br />
    <%= f.text_field :cp %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :ville %><br />
    <%= f.text_field :ville %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :fixe %><br />
    <%= f.text_field :fixe %>
  </div>
  <div class="field" id="formClient">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field" id="formClient">
  <%= f.label :commentaire %><br/>
  <%= f.text_area :commentaire %>
  </div>
  <br/><br/>
  <div class="actions" id="submitClient">
    <%= f.submit "S'inscrire" %>
  </div>
</div>
<div id="right">
	<%= image_tag "exunImagesFiles/panneau-form.png", :style => "margin-left: 80px; margin-top: 0px; margin-bottom: 20px; height: 430px" %>
</div>
<div style="clear: both;"></div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Adresse</th>
    <th>Complement</th>
    <th>Cp</th>
    <th>Ville</th>
    <th>Email</th>
    <th>Fixe</th>
    <th>Mobile</th>
    <th>Etat</th>
    <th>Commercial</th>
    <th>Commentaire</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.nom %></td>
    <td><%= contact.prenom %></td>
    <td><%= contact.adresse %></td>
    <td><%= contact.complement %></td>
    <td><%= contact.cp %></td>
    <td><%= contact.ville %></td>
    <td><%= contact.email %></td>
    <td><%= contact.fixe %></td>
    <td><%= contact.mobile %></td>
    <td><%= contact.etat %></td>
    <td><%= contact.commercial %></td>
    <td><%= contact.commentaire %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>Formulaire d'insciption</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @contact.nom %>
</p>

<p>
  <b>Prenom:</b>
  <%= @contact.prenom %>
</p>

<p>
  <b>Adresse:</b>
  <%= @contact.adresse %>
</p>

<p>
  <b>Complement:</b>
  <%= @contact.complement %>
</p>

<p>
  <b>Cp:</b>
  <%= @contact.cp %>
</p>

<p>
  <b>Ville:</b>
  <%= @contact.ville %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Fixe:</b>
  <%= @contact.fixe %>
</p>

<p>
  <b>Mobile:</b>
  <%= @contact.mobile %>
</p>

<%= link_to 'Editer vos informations', edit_contact_path(@contact) %> |
<%= link_to 'retour', root_path %>

app/views/grandprojet/index.html.erb
<div id="left"><h1>Grands Projets </h1><span class="blue"> </span><br/>
    <br/>
	<ul>
	<li>Location de toiture

	<li>Construction de bâtiments industriels</li>
	</ul>
</div>
<div id="right"><br/>
	<photo><%= image_tag "exunImagesFiles/centrale-photo.jpg", :width => "225", :height => "149", :align => "left", :style => "margin-right:10px" %></photo>
	<photo><%= image_tag "exunImagesFiles/panneau-cereales.jpg", :width => "225", :height => "149", :align => "left", :style => "margin-right:10px" %></photo>
	<br/><br/><br/>
</div><br/>
<div style="clear: both;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helios Energeia</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
    <body>

        <div id="header">
            <%= image_tag "banHelios.png" %>
        </div>
	
<div id="menu">
	<ul>
		<li><%= link_to"Accueil", root_path %></li>
		<li><%= link_to"Qui sommes-nous", whoarewe_index_path %><li>
		<li><a href="/inprogress.html"  title="" >Services</a></li> <!-- <%= link_to"Services", services_index_path %> -->
		<li><a href="/inprogress.html"  title="" >Solutions</a></li>
		<li><%= link_to"Grands projets", grandprojet_index_path %></li>
		<li><%= link_to("Être contacté", new_contact_path) %></li>
		<li><a href="/inprogress.html"  title="" >Admin</a></li> <!-- <%= link_to "Admin", contacts_path %> -->
	</ul>
	
</div>


            <div id="content">
                <%= yield %>
            </div>
            <div id="footer">
                <p>Copyright &copy; 2012 Helios Energia.</p>
            </div>

        </div>
    </body>
</html>

app/views/services/index.html.erb
<h1>Services#index</h1>
<p>Find me in app/views/services/index.html.erb</p>

app/views/whoarewe/index.html.erb
<div id="right"><h1>Qui sommes-nous </h1><span class="blue"> </span><br/>
    <br/>
    Société à caractère commerciale s'entourant des principaux acteurs de la région pour fournir des solutions clé en main de production et d'économie 
	d'énergie.<br/>
	<ul>
	<li>Solaire, photovoltaïque
	<li>Chauffe-eau solaire
	<li>Pompe à chaleur
	</ul>
	<br/><br/>
</div>
<div style="clear: both;"></div>